spring.application.name=remitly-task
spring.sql.init.mode=always
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:market;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
